# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCodeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, verbose_name='用户邮箱')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('code_type', models.CharField(choices=[('1', 'register'), ('2', 'reset'), ('3', 'changeemail'), ('4', 'sendpwd')], max_length=100, verbose_name='验证码类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '验证码信息表',
                'verbose_name_plural': '验证码信息表',
            },
        ),
    ]
