# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentinfo',
            name='comment_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='arttag',
            name='articleinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleInfo', verbose_name='所属文章'),
        ),
        migrations.AddField(
            model_name='arttag',
            name='taginfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.TagInfo', verbose_name='所属标签'),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文章作者'),
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='所属类别'),
        ),
        migrations.AlterUniqueTogether(
            name='arttag',
            unique_together=set([('articleinfo', 'taginfo')]),
        ),
    ]
