# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180921_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_tab',
            field=models.BooleanField(default=True, verbose_name='是否导航'),
        ),
    ]
