# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_category_is_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='类别标题'),
        ),
    ]
