# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='路径别名'),
        ),
    ]
