# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_category_path_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='首页推荐'),
        ),
    ]
