# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articleinfo_is_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='image',
            field=models.ImageField(default='article/default.jpg', max_length=200, upload_to='article/%y/%m/%d', verbose_name='封面'),
        ),
    ]
