# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180922_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='taginfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='所属类别'),
        ),
    ]
