# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 19:21
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_taginfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容'),
        ),
    ]
