# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20190825_1730'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arttag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='arttag',
            name='articleinfo',
        ),
        migrations.RemoveField(
            model_name='arttag',
            name='taginfo',
        ),
        migrations.AlterField(
            model_name='articleinfo',
            name='image',
            field=models.ImageField(blank=True, default='article/default5.jpg', max_length=200, null=True, upload_to='article/%y/%m/%d', verbose_name='封面'),
        ),
        migrations.DeleteModel(
            name='ArtTag',
        ),
    ]
