# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-10 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20190825_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='image',
            field=models.ImageField(blank=True, default='article/default4.jpg', max_length=200, null=True, upload_to='article/%y/%m/%d', verbose_name='封面'),
        ),
    ]
